Fix squad relationships
AirsoftClub/airsoftclub pull request #7
Opened 2024-02-18 11:42 UTC by conradogarciaberrotaran

2024-02-18 18:53 UTC, ArtemKozak requested changes
Really great work done, thanks!

2024-02-18 18:53 UTC, artemkozak commented on backend/.python-version
Please create a .python-version.example file with the same content

2024-02-18 18:53 UTC, artemkozak commented on backend/.pre-commit-config.yaml
> -  - repo: https://github.com/ambv/black
What is the reason of removing `black` linter?

2024-02-18 18:53 UTC, artemkozak commented on backend/Dockerfile
>  RUN pip3 install "poetry==1.6.1"
Latest version is `"poetry==1.7.1"` ([PyPi Poetry](https://pypi.org/project/poetry/))

2024-02-18 18:53 UTC, artemkozak commented on backend/README.md
>  To ensure the quality of the code, follow these steps to run the tests:
```suggestion
There are 2 types of tests available:
- Unit tests;
- System tests.

To ensure the quality of the code, follow these steps to run the tests:
```

2024-02-18 18:53 UTC, artemkozak commented on backend/app/endpoints/auth.py
>          raise HTTPException(status_code=404, detail="User not found")
It's better to have same error for checking email and pasword on login:
```suggestion
        raise HTTPException(status_code=401, detail="Invalid credentials")
```

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/auth.py
>      if not Hash.verify(user.password, db_user.password):
Move password verifying to User class, `services/user.py` or separate method to be incapsulated

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/auth.py
> +    user_repository.db.commit()
```suggestion
    user_repository.create(user)
```

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/auth.py
Bad naming for method [`generate_token_family_from_refresh`](https://github.com/AirsoftClub/airsoftclub/blob/e6250a852b7efaaf516fdb0c24bea222ee4c6ea1/backend/app/security/auth.py#L68)

Suggestion: rename to `generate_token_family_from_old_token` or  `generate_refresh_family_from_token` or `generate_new_family_from_token`

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/auth.py
>  ):
Please add for each method doc strings similar to `backend/app/endpoints/squads.py`

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/squads.py
> +    if not squad:
Based on `backend/app/endpoints/auth.py` change here to:

```suggestion
    if squad is None:
```

Or in `backend/app/endpoints/auth.py` change to `if not [PARAM]:`

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/squads.py
> +        raise HTTPException(status_code=403, detail="You are not the owner")
```suggestion
        raise HTTPException(status_code=403, detail="You are not the owner of this squad")
```

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/squads.py
>  ):
Please add doc string for router endpoint methods, espesially which potencial errors they can raise. This will help in unit and system testing.

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/squads.py
> +        raise HTTPException(status_code=400, detail="User already invited")
No need to raise an error. Possibly, later here will be a notification service.
Update incitation `updated_at` and return `return {"message": "User invited"}`

```suggestion
        # touch `updated_at` field here
        return {"message": "User invited"}
```

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/squads.py
> +        raise HTTPException(status_code=404, detail="User not found")
Since this is commonly used lines, move them to separate method `get_user` and add as `Depend(get_user)`.

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/squads.py
> +@router.delete("/{squad_id}")
Add the resonse model:
```suggestion
@router.delete("/{squad_id}", response_model=...)
```

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/squads.py
> +@router.put("/{squad_id}")
```suggestion
@router.put("/{squad_id}", response_model=...)
```

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/squads.py
> +@router.post("/{squad_id}/avatar")
```suggestion
@router.post("/{squad_id}/avatar", response_model=...)
```

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/users.py
> +):
Doc strings

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/squads.py
>      return squad_repository.add_squad_avatar(squad, avatar)
Check in the method for allowed images types (similar to `backend/app/endpoints/users.py#avatar`):
```python
if avatar.content_type not in ["image/jpeg", "image/png"]:
        raise HTTPException(status_code=400, detail="Invalid file type")
```

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/users.py
>  @router.post("/me/avatar", response_model=UserResponse)
Move avatar upload to user repository

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/endpoints/users.py
> +    # TODO: Fix this
What's wrong?

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/repositories/squads.py
> +        )  # TODO: Should we count deleted?
Nope, if squad is deleted, it should not be listed / counted. Restoring of accidential deletion could be done via support.

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/repositories/squads.py
> +        )  # TODO: Should we count deleted?
Probably, we should consider adding default scope with `.filter(Squad.deleted_at.is_(None))`

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/repositories/squads.py
> +            # Remove invitations for this user
Remove or update `deleted_at`?

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/repositories/squads.py
> +            # Remove invitations for this user
Same here

2024-02-18 18:53 UTC, ArtemKozak commented on backend/app/repositories/users.py
> +        if payload.name:
Just as an option for dynamic updates:
```python
for attr in allowed_attrs:
        if hasattr(payload, attr):
            new_value = getattr(payload, attr)
            if new_value is not None:
                setattr(user, attr, new_value)
```

2024-02-18 20:00 UTC, conradogarciaberrotaran commented on backend/.pre-commit-config.yaml
> -  - repo: https://github.com/ambv/black
ruff and black do the same, and are sometimes incompatible

2024-02-18 20:04 UTC, conradogarciaberrotaran commented on backend/app/repositories/squads.py
> +            # Remove invitations for this user
I would delete it, otherwise you won't be able to re-invite someone to the squad.

2024-02-18 20:07 UTC, conradogarciaberrotaran commented on backend/app/endpoints/auth.py
>      if not Hash.verify(user.password, db_user.password):
This PR was supposed to be only for squad logic, let's do this in other PR.

2024-02-18 20:07 UTC, conradogarciaberrotaran commented on backend/app/endpoints/auth.py
This PR was supposed to be only for squad logic, let's do this in other PR.

2024-02-18 20:08 UTC, conradogarciaberrotaran commented on backend/app/endpoints/squads.py
>  ):
This PR was supposed to be only for squad logic, let's do this in other PR.

2024-02-18 20:09 UTC, conradogarciaberrotaran commented on backend/app/endpoints/squads.py
> +        raise HTTPException(status_code=400, detail="User already invited")
updated_at will be automatically updated. removed the if statement.

2024-02-19 10:05 UTC, conradogarciaberrotaran commented on backend/.python-version
python version is automatically created when you do
```shell
pyenv local <venv_name>
```
it's not something you have to manually create.

2024-02-19 10:07 UTC, conradogarciaberrotaran commented on backend/app/endpoints/squads.py
> +        raise HTTPException(status_code=404, detail="User not found")
only 2 times we fetch for an external user (different from the current_user).
on invite_user by email and on update_application by user_id.
we cant generalize here.

2024-02-19 10:08 UTC, conradogarciaberrotaran commented on backend/app/endpoints/squads.py
> +@router.delete("/{squad_id}")
delete should not have a response, changing it to 204.

2024-02-19 10:09 UTC, conradogarciaberrotaran commented on backend/app/endpoints/squads.py
> +@router.put("/{squad_id}")
fixed

2024-02-19 10:10 UTC, conradogarciaberrotaran commented on backend/app/endpoints/squads.py
> +@router.post("/{squad_id}/avatar")
Will re-work this on file handling PR.

2024-02-19 10:11 UTC, conradogarciaberrotaran commented on backend/app/endpoints/squads.py
>      return squad_repository.add_squad_avatar(squad, avatar)
will work on this on file handling PR.

2024-02-19 10:13 UTC, conradogarciaberrotaran commented on backend/app/repositories/users.py
> +        if payload.name:
it's dangerous to set attributes to an ORM without comprobation, I would leave it as is.
if it gets too big, we implement something for partial updates.

2024-02-19 10:14 UTC, conradogarciaberrotaran commented on backend/app/repositories/squads.py
> +        )  # TODO: Should we count deleted?
done.

2024-02-19 10:15 UTC, conradogarciaberrotaran commented on backend/app/endpoints/users.py
> +    # TODO: Fix this
update now expects a payload, will fix this in file handling PR.

2024-02-19 10:15 UTC, conradogarciaberrotaran commented on backend/app/endpoints/users.py
>  @router.post("/me/avatar", response_model=UserResponse)
will be fixed in file handling PR.

2024-02-19 12:59 UTC, ArtemKozak approved these changes

2024-02-19 13:00 UTC, merged